server:
  port: 8090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      
logging:
  level:
    com: 
      fasterxml:
        jackson:
          databind: DEBUG
      
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ezpick_db?serverTimezone=Asia/Seoul
    username: admin
    password: admin1234
    
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate.format_sql: true 